CREATE TABLE "QP_Payments" (
"UniqueId" NVARCHAR2(50) NOT NULL,
"PayPlatId" NUMBER(11,0) NOT NULL,
"AppId" NVARCHAR2(50) NOT NULL,
"OutTradeNo" NVARCHAR2(50) NOT NULL,
"TradeType" NVARCHAR2(20) NOT NULL,
"BusinessCode" NVARCHAR2(20) NOT NULL,
"TransactionId" NVARCHAR2(50) NULL,
"Amount" NUMBER NULL,
"PayStatusId" NUMBER(11,0) NOT NULL,
"PayObject" NCLOB NULL,
"Describe" NVARCHAR2(1000) NULL,
PRIMARY KEY ("UniqueId") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE INDEX "QP_P_UniqueId" ON "QP_Payments" ("UniqueId" ASC);

CREATE TABLE "QP_Refunds" (
"UniqueId" NVARCHAR2(50) NOT NULL,
"PayPlatId" NUMBER(11,0) NOT NULL,
"AppId" NVARCHAR2(50) NOT NULL,
"OutTradeNo" NVARCHAR2(50) NOT NULL,
"TransactionId" NVARCHAR2(50) NOT NULL,
"OutRefundNo" NVARCHAR2(50) NOT NULL,
"RefundAmount" NUMBER NOT NULL,
"RefundId" NVARCHAR2(50) NULL,
"PayObject" CLOB NULL,
"Describe" NCLOB NULL,
PRIMARY KEY ("UniqueId") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE INDEX "QP_R_UniqueId" ON "QP_Refunds" ("UniqueId" ASC);

